"""adicionado a coluna hash a tabela compras

Revision ID: 0a99cd5e63be
Revises: 437a02c14363
Create Date: 2026-08-25 05:49:04.452620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a99cd5e63be'
down_revision = '437a02c14363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('hash')

    # ### end Alembic commands ###
