"""Initial Migration - Tabela Users

Revision ID: 430e4acc1391
Revises: 
Create Date: 2026-08-12 04:50:43.053388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430e4acc1391'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
