"""criada tabela categorias e colunas data e categoria_id em Compras

Revision ID: 437a02c14363
Revises: e67642e38041
Create Date: 2026-08-18 23:06:31.392970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437a02c14363'
down_revision = 'e67642e38041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_compras_categoria_id', 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_constraint('fk_compras_categoria_id', type_='foreignkey')
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('data')

    op.drop_table('categorias')
    # ### end Alembic commands ###
