"""empty message

Revision ID: 6f3e5a3d3865
Revises: ad2f0ae38b7f
Create Date: 2026-08-17 00:38:26.052017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3e5a3d3865'
down_revision = 'ad2f0ae38b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
