"""remove constraint unique da coluna hash da tabela compras

Revision ID: 9b43914e86bd
Revises: f26360cc8de0
Create Date: 2026-09-01 04:23:34.429402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b43914e86bd'
down_revision = 'f26360cc8de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_hash'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_hash'), ['hash'])

    # ### end Alembic commands ###
