"""adicionadas as tabelas saidas, bancos e saldos

Revision ID: ad2f0ae38b7f
Revises: 0cbf6fac9a17
Create Date: 2026-08-17 00:38:17.802286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2f0ae38b7f'
down_revision = '0cbf6fac9a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ano >= 2026', name='check_ano_v'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='check_mes_v'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ano >= 2026', name='check_ano'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='check_mes'),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'banco_id', 'user_id', name='unique_ano_mes_banco_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos')
    op.drop_table('saidas')
    op.drop_table('bancos')
    # ### end Alembic commands ###
