"""coluna hash unique True

Revision ID: bda63df4d772
Revises: 0a99cd5e63be
Create Date: 2026-08-25 17:04:04.661732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda63df4d772'
down_revision = '0a99cd5e63be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_hash', ['hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_constraint('unique_hash', type_='unique')

    # ### end Alembic commands ###
