"""adicionadas as tabelas faturas e compras

Revision ID: ce8e437cafa6
Revises: 6f3e5a3d3865
Create Date: 2026-08-17 01:03:06.224412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce8e437cafa6'
down_revision = '6f3e5a3d3865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('status_paga', sa.Boolean(), nullable=False),
    sa.CheckConstraint('ano >= 2026', name='check_ano_fatura'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='check_mes_fatura'),
    sa.CheckConstraint('status_paga IN (0,1)', name='check_bool'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banco_id'], ['bancos.id'], ),
    sa.ForeignKeyConstraint(['fatura_id'], ['faturas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saldos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('saldo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('valor')

    op.drop_table('compras')
    op.drop_table('faturas')
    # ### end Alembic commands ###
