"""coluna valor de compras virou valor_total

Revision ID: ddd89944e3ab
Revises: ce8e437cafa6
Create Date: 2026-08-18 04:49:52.766976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd89944e3ab'
down_revision = 'ce8e437cafa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('valor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###
