"""criada coluna valor_parcela

Revision ID: e67642e38041
Revises: ddd89944e3ab
Create Date: 2026-08-18 04:51:40.530275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67642e38041'
down_revision = 'ddd89944e3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_parcela', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('valor_parcela')

    # ### end Alembic commands ###
