"""criada coluna cartao na tabela bancos

Revision ID: f26360cc8de0
Revises: bda63df4d772
Create Date: 2026-08-30 23:09:39.904112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26360cc8de0'
down_revision = 'bda63df4d772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cartao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bancos', schema=None) as batch_op:
        batch_op.drop_column('cartao')

    # ### end Alembic commands ###
